// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  image: dynamic(() => import("./Image")),
  ingredients: dynamic(() => import("./Ingredients")),
  quote: dynamic(() => import("./Quote")),
  restaurant_details: dynamic(() => import("./RestaurantDetails")),
  text: dynamic(() => import("./Text")),
};
